# Generated by Django 2.2.16 on 2021-12-18 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20211218_1320'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
